fa: # path to reference genome
gtf: # path to annotation
tr: # path to transcripts
fq1: # path to first pair
fq2: # path to second pair
odir: # path to output directory
threads: # n. threads
galig: # path to galig repository
