#!/bin/bash

genomic=$1
annotation=$2
rnaseqs=$3
L=$4
K=$5
out=$6
WD=$7

HD=~/Projects/galig

mkdir -p ${WD}
cd ${WD}

rm -rf ./tmp/
mkdir -p ./tmp/

rm -rf ${out}
mkdir -p ${out}
echo "Preprocessing..."
python3 ${HD}/scripts/prepareInput.py ${genomic} ${annotation} ${WD}
echo "MEMs Computation..."
/usr/bin/time -v --append --output=mems.time ${HD}/bMEM/backwardMEM -l=${L} ./tmp/T.fa ${rnaseqs} &> ./tmp/mems
rm ./stopwatch.txt
rm ./lock.txt

echo "Aligning..."
mkdir -p ${WD}/${out}
/usr/bin/time -v --append --output=align.time bash -c "${HD}/bin/main ./tmp/mems ./tmp/e_lens ./tmp/real_edges ./tmp/added_edges ${L} ${K} ${WD}/${out}/$out ; python3 ${HD}/scripts/SAMFormatter.py ${WD}/${out}/${out} ${rnaseqs}"

echo "Postprocessing..."
python3 ${HD}/scripts/formatter.py ${WD}/${out}/${out}
python3 ${HD}/scripts/edgesFormatter.py ${WD}/${out}/${out}
python3 ${HD}/scripts/newEdgesFormatter.py ${WD}/${out}/${out}

#rm -rf ./tmp/

#samtools view -bS $out.sam > $out.bam

#samtools sort $out.bam $out.sort
#samtools index $out.sort.bam
