#!/bin/bash

genomic=$1
annotation=$2
rnaseqs=$3
L=$4
K=$5
out=$6
perc=$7

rm -rf ./tmp/
mkdir -p ./tmp/

rm -rf ./out/
mkdir -p ./out/

python3 ./scripts/prepareInput.py $genomic $annotation
./bMEM/backwardMEM -l=$L ./tmp/T.fa $rnaseqs &> ./tmp/mems
rm ./stopwatch.txt
rm ./lock.txt
./bin/main ./tmp/mems ./tmp/e_lens ./tmp/edges $K $out $perc
