#!/bin/bash

WD=$(pwd)

while getopts ":g:a:r:l:e:o:" opt; do
    case $opt in
        g)
            genome=$OPTARG
            ;;
        a)
            annotation=$OPTARG
            ;;
        r)
            samples=$OPTARG
            ;;
        l)
            L=$OPTARG
            ;;
        e)
            e=$OPTARG
            ;;
        o)
            outFold=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

IFS=',' read -r -a samplesArray <<< ${samples}

mkdir -p ${outFold}
events=""
for sample in "${samplesArray[@]}"
do
    echo ${sample}
    name=$(basename ${sample%\.*})
    out=${outFold}/${name}.aligns
    event=${outFold}/${name}.events
    ${WD}/bin/main -g ${genome} -a ${annotation} -r ${sample} -l ${L} -e ${e} -o ${out}
    python3 ${WD}/scripts/SAMFormatter.py ${out} ${annotation}.sg ${sample}
    python3 ${WD}/scripts/postprocessing.py ${annotation}.sg ${out} > ${event}
    events="${events} ${event}"
done

python3 ${WD}/scripts/compareEvents.py ${events} > ${outFold}/comparison.csv
