#!/bin/bash

l=7 #(30 15 7)
k=5
p=75

while read gene; do
    echo "### "$gene" ###"
    mkdir -p /home/prj_gralign/data/Toxo_res/0301/$l/$k/$p/
    /usr/bin/time -v -o /home/prj_gralign/data/Toxo_res/${gene}_${l}_${k}_${p}.time ./run ~/data/Toxoplasma/genomic.fasta ~/data/Toxoplasma/Genes_200/$gene/$gene.gff ~/data/Toxoplasma/Genes_200/$gene/$gene.fa $l $k /home/prj_gralign/data/Toxo_res/0301/$l/$k/$p/${gene} 0.$p
done < 75
